biblioteca/urls.py
from django.urls import path
from .views.document_views import  (
    ListDocuments,
    DocumentUpdateView,
    DocumentCreateView,
    DocumentDeleteView,
    ListDocumentsCustomView,
    ReadDocumentView,
)
from .views.user_views import (
    UserListView,
    CreateUserView,
    CreatedSuccessfullUser
)
from .views.order_views import (
    ListOrders,
    SubmitPrintOrderView,
    ApproveOrder,
    RejectOrder,
    ListOrdersHistory,
)
from .views.courses_views import (
    CoursesView,
    DeleteCourseView
)
from .views.profile_views import ProfileView
from .views.dashboard_views import DashboardAdminView
from .views.login_views import LoginView

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('admin/', DashboardAdminView.as_view(), name='admin_dashboard'),
    path('admin/documentos', ListDocuments.as_view(), name='documents'),
    path('admin/documentos/registar', DocumentCreateView.as_view(), name='documents.register'),
    path('admin/documentos/<int:doc>/excluir', DocumentDeleteView.as_view(), name='document.delete'),
    path('admin/documentos/<int:doc>/editar', DocumentUpdateView.as_view(), name='document.edit'),
    path('admin/pedidos', ListOrders.as_view(), name='orders'),
    path('admin/pedidos/<int:id>/aprovar', ApproveOrder.as_view(), name='orders.approve'),
    path('admin/pedidos/<int:id>/rejeitar', RejectOrder.as_view(), name='orders.reject'),
    path('admin/utilizadores', UserListView.as_view(), name='users'),
    path('admin/utilizadores/registar', CreateUserView.as_view(), name='users.register'),
    path('admin/utilizadores/criado-com-sucesso', CreatedSuccessfullUser.as_view(), name='users.successfully'),
    path('admin/cursos', CoursesView.as_view(), name='courses'),
    path('admin/cursos/<int:id>/excluir', DeleteCourseView.as_view(), name='courses.delete'),
    path('perfil', ProfileView.as_view(), name="profile"),
    ###Rotas dos Estudante/Docente
    path('documentos',ListDocumentsCustomView.as_view(), name='documents.custom'),
    path('documentos/<int:id>/submeter-pedido', SubmitPrintOrderView.as_view(), name='order.submit'),
    path('documento/<int:id>/leitura', ReadDocumentView.as_view() , name='documents.read'),
    path('historico-pedidos',ListOrdersHistory.as_view(), name="orders.history"),
]

biblioteca_virtual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.admin import site
from django.contrib.auth import views as auth_views
from django.views.decorators.cache import never_cache
from django.conf import settings
from django.conf.urls.static import static

# Para garantir que a view admin login funciona corretamente
admin_login = never_cache(site.login)

urlpatterns = [
    path('', include('biblioteca.urls')),
    path('secret/', admin.site.urls),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biblioteca/models.py
from django.contrib.auth.models import AbstractUser,Group
from django.db import models

# User = get_user_model()


# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    def __str__(self) :
        return self.name
    
class User(AbstractUser):
    student_code = models.CharField(max_length=20, blank=True, null=True)
    phone = models.CharField(max_length=10)
    course = models.ForeignKey(Course, blank=True, null=True, on_delete=models.SET_NULL)
    
class Subject(models.Model):
    name = models.CharField(max_length=255)
    course = models.ForeignKey(Course, on_delete=models.CASCADE,related_name='subject_to_course')
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return self.name
    
class Document(models.Model):
    TYPE_CHOICES = [
        ('livros', 'Livros'),
        ('artigos','Artigos'),
        ('teses', 'Teses'),
        ('revistas', 'Revistas')
    ]

    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    year = models.IntegerField()
    link = models.FileField(upload_to='documentos/')
    description = models.TextField()
    isdownloaded = models.BooleanField(default=False)
    slug = models.SlugField(max_length=255, blank=True, null=True)
    type = models.CharField(max_length=20, choices=TYPE_CHOICES, default='livros')
    course = models.ForeignKey(Course,on_delete=models.CASCADE,related_name="documento_to_course")
    score = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return self.title
    
class Order(models.Model):
    STATUS_CHOICES = [
        ('pendente', 'Pendente'),
        ('aprovado', 'Aprovado'),
        ('rejeitado', 'Rejeitado'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    copy_total = models.IntegerField()
    first_page = models.IntegerField()
    last_page = models.IntegerField()
    document = models.ForeignKey(Document, on_delete=models.CASCADE, related_name='orders')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pendente")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Pedido #{self.id} (Usuário {self.user.username})"

class BlockedUser(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="block_user")
    reason = models.TextField()
    is_blocked = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return self.reason

class AcessDocStatistic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='statistics_user')
    document = models.ForeignKey(Document, on_delete=models.CASCADE, related_name='statistics_doc')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Estatística #{self.id} (Usuário {self.user.username})"
    
class DocumentGroup(models.Model):
    group = models.ForeignKey(Group, on_delete=models.DO_NOTHING, related_name="document_group_permissios")
    document = models.ForeignKey(Document, on_delete=models.DO_NOTHING, related_name="group_document_permissions")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

biblioteca/views.py
from django.shortcuts import render

# write your views here

biblioteca/views/courses_views.py
from django.views import View
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect, get_object_or_404
from ..models import Course

class CoursesView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'admin/courses.html'
    
    def test_func(self):
        # Só permite se o usuário estiver no grupo "Bibliotecario"
        return self.request.user.groups.filter(name='Bibliotecario').exists()

    def handle_no_permission(self):
        from django.shortcuts import redirect
        # Redireciona se o usuário não tiver permissão (por grupo, por exemplo)
        return redirect('documents.custom')  # ou outra página como "sem_permissao"

    def get(self, request): 
       courses = Course.objects.all()
       return render(request, self.template_name, {'courses':courses})
   
    def post(self, request):
        course_id = request.POST.get('course_id') 
        course_name = request.POST.get('course', '').strip()

        # Validação: campo vazio
        if not course_name:
            messages.error(request, "O nome do curso é obrigatório.")
            return redirect('courses')

        # Se for edição (course_id enviado)
        if course_id:
            try:
                course = Course.objects.get(id=course_id)

                # Validação: nome duplicado (exceto se for o mesmo curso)
                if Course.objects.filter(name__iexact=course_name).exclude(id=course_id).exists():
                    messages.error(request, "Já existe outro curso com esse nome.")
                    return redirect('courses')

                course.name = course_name
                course.save()
                messages.success(request, "Curso atualizado com sucesso.")
            except Course.DoesNotExist:
                messages.error(request, "Curso não encontrado.")
        else:
            # Criação
            if Course.objects.filter(name__iexact=course_name).exists():
                messages.error(request, "Já existe um curso com esse nome.")
                return redirect('courses')

            Course.objects.create(name=course_name)
            messages.success(request, "Curso criado com sucesso.")

        return redirect('courses')
    
class DeleteCourseView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'admin/confirm-delete-course.html'
    
    def test_func(self):
        # Só permite se o usuário estiver no grupo "Bibliotecario"
        return self.request.user.groups.filter(name='Bibliotecario').exists()

    def handle_no_permission(self):
        from django.shortcuts import redirect
        # Redireciona se o usuário não tiver permissão (por grupo, por exemplo)
        return redirect('documents.custom')  # ou outra página como "sem_permissao"
    
    def get(self, request, id):
        course = get_object_or_404(Course, id=id)
        return render(request, self.template_name, {'course':course})
    
    def post(self, request, id):
        course = get_object_or_404(Course, id=id)
        course.delete()
        return redirect('courses')
        
 

biblioteca/views/dashboard_views.py
import locale
from django.views import View
from ..dashboard_service import (
    get_recent_users,
    get_documents_this_month,
    get_order_status_counts,
    calculate_order_completion_percentage,
    get_access_stats_by_month,
    get_recent_access,
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.utils import timezone
from biblioteca.models import Document, User, Order, AcessDocStatistic

class DashboardAdminView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'admin/dashboard.html'
    
    def test_func(self):
        # Só permite se o usuário estiver no grupo "Bibliotecario"
        return self.request.user.groups.filter(name='Bibliotecario').exists()

    def handle_no_permission(self):
        from django.shortcuts import redirect
        # Redireciona se o usuário não tiver permissão (por grupo, por exemplo)
        return redirect('login')  # ou outra página como "sem_permissao"

    def get(self, request):
        total_users = User.objects.count()
        total_documents = Document.objects.count()
        total_orders = Order.objects.count()
        total_access = AcessDocStatistic.objects.count()
        recent_users = get_recent_users()
        documents_this_month = get_documents_this_month()
        order_status_counts = get_order_status_counts()
        status_counts = {item['status']: item['count'] for item in order_status_counts}
        total_orders_complete = calculate_order_completion_percentage(status_counts, total_orders)
        access_stats_by_month = get_access_stats_by_month()
        locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8') 
        total_access_recent = get_recent_access()

        context = {
            'recent_users': recent_users,
            'documents_this_month': documents_this_month,
            'current_month_year': timezone.now().strftime('%B'),
            'total_users': total_users,
            'total_documents': total_documents,
            'total_orders': total_orders,
            'total_orders_complete': total_orders_complete,
            'access_stats_by_month': access_stats_by_month,
            'total_access' : total_access,
            'total_access_recent': total_access_recent
        }
        return render(request, self.template_name, context)

biblioteca/views/login_views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect
from django.views.generic import FormView

class LoginView(FormView):
    template_name = 'login.html'
    form_class = AuthenticationForm # Usa o formulário de autenticação padrão do Django

    # O método 'get' é automaticamente tratado por FormView para exibir o formulário.
    # O método 'post' é automaticamente tratado por FormView para validar o formulário.

    def form_valid(self, form):
        # Este método é chamado quando o formulário é válido (usuário e senha corretos).
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')

        user = authenticate(self.request, username=username, password=password)

        if user is not None:
            login(self.request, user)

            # Pega os grupos do usuário
            grupos = user.groups.values_list('name', flat=True)

            # Redireciona com base no grupo
            if 'Bibliotecario' in grupos:
                messages.success(self.request, f"Bem-vindo(a), {user.first_name}!")
                return redirect('admin_dashboard')
            elif 'Registo Academico' in grupos:
                messages.success(self.request, f"Bem-vindo(a), {user.first_name}!")
                return redirect('admin_dashboard')
            elif 'Estudante' in grupos:
                messages.success(self.request, f"Bem-vindo(a), {user.first_name}!")
                return redirect('documents.custom')
            elif 'Docente' in grupos:
                messages.success(self.request, f"Bem-vindo(a), {user.first_name}!")
                return redirect('documents.custom')
            
            # Fallback para usuários sem grupo específico ou caso nenhum match seja encontrado
            messages.success(self.request, f"Bem-vindo(a), {user.first_name}!")
            return redirect('default_dashboard') # Certifique-se de que esta URL existe

        else:
            # Isso não deve acontecer com AuthenticationForm, pois ele já valida as credenciais
            # antes de chamar form_valid. No entanto, é um fallback de segurança.
            messages.error(self.request, 'Credenciais inválidas. Verifique seu nome de usuário e senha.')
            return self.form_invalid(form) # Renderiza o formulário com erros se algo deu errado aqui
            
    def form_invalid(self, form):
        # Este método é chamado quando o formulário é inválido (usuário ou senha incorretos).
        # AuthenticationForm já adiciona os erros ao formulário.
        messages.error(self.request, 'Nome de usuário ou senha incorretos.')
        return super().form_invalid(form) # Renderiza o template com o formulário e os erros

biblioteca/views/profile_views.py
from django.views import View
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render, redirect, get_object_or_404
from biblioteca.models import User

class ProfileView(LoginRequiredMixin, View):
    template_name = 'profile.html'

    def get(self, request):
        user = get_object_or_404(User, id=request.user.id)
        return render(request, self.template_name, {'user': user})

    def post(self, request):
        user = request.user

        # Verifica se é atualização de perfil ou troca de senha
        if 'oldpassword' in request.POST:
            # Alteração de senha
            old_password = request.POST.get('oldpassword')
            new_password = request.POST.get('password')
            confirmation_password = request.POST.get('confirmation_password')

            if not user.check_password(old_password):
                messages.error(request, "Senha antiga incorreta.")
            elif new_password != confirmation_password:
                messages.error(request, "As novas senhas não coincidem.")
            elif len(new_password) < 6:
                messages.error(request, "A nova senha deve ter pelo menos 6 caracteres.")
            else:
                user.set_password(new_password)
                user.save()
                update_session_auth_hash(request, user)  # Mantém o login ativo
                messages.success(request, "Senha alterada com sucesso.")

        else:
            # Atualização de perfil
            first_name = request.POST.get('firstname', '').strip()
            last_name = request.POST.get('lastname', '').strip()
            email = request.POST.get('email', '').strip()
            phone = request.POST.get('phone', '').strip()

            if not first_name or not last_name or not email or not phone:
                messages.error(request, "Preencha todos os campos.")
            else:
                user.first_name = first_name
                user.last_name = last_name
                user.email = email
                user.phone = phone
                user.save()
                messages.success(request, "Perfil atualizado com sucesso.")

        return redirect('profile')  # Certifique-se que 'profile' está definido no urls.py

biblioteca/templates/custom/create-order.html
{% extends 'layouts/app.html' %}

{% block title %}Pedido de Impressão{% endblock %}

{% block content %}
{% load static %}
<div class="mt-3 ms-3">
    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);"
        aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'documents.custom' %}">Inicio</a></li>
            <li class="breadcrumb-item active" aria-current="page">Pedido de Impressão</li>
        </ol>
    </nav>
</div>
<div class="p-3 d-flex justify-content-center align-items-center">
    <div class="card shadow border border-0 p-3">
        <h2>Pedido de Impressão</h2>
        <div class="row">
            <div class="col-md-3 me-2">
                <ul class="list-unstyled">
                    <li class="row py-1 border-bottom">
                        <div class="col-4 fw-bold">Título:</div>
                        <div class="col-8 text-end">{{ document.title }}</div>
                    </li>
                    <li class="row py-1 border-bottom">
                        <div class="col-4 fw-bold">Autor:</div>
                        <div class="col-8 text-end">{{ document.author }}</div>
                    </li>
                    <li class="row py-1 border-bottom">
                        <div class="col-4 fw-bold">Ano:</div>
                        <div class="col-8 text-end">{{ document.year }}</div>
                    </li>
                    <li class="row py-1 border-bottom">
                        <div class="col-4 fw-bold">Tipo:</div>
                        <div class="col-8 text-end">{{ document.type }}</div>
                    </li>
                </ul>

            </div>
            <div class="col-md-7">
                <form id="formUsuario" method="post" validate>
                    {% csrf_token %}
                    <div class="row gap-2">
                        <div class="row mt-2">
                            <div class="col-md-12">
                                <label for="copy_total" class="form-label">Numero de Copias</label>
                                <input type="number" class="form-control" id="copy_total" name="copy_total"
                                    placeholder="Insira o numero de copias" min="1" required />
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-md-6">
                                <label for="firstpage" class="form-label">Começar na página:</label>
                                <input type="number" class="form-control" id="firstpage" name="firstpage"
                                    placeholder="Ex: 1" min="1" required />
                            </div>
                            <div class="col-md-6">
                                <label for="lastpage" class="form-label">Terminar na página:</label>
                                <input type="number" class="form-control" id="lastpage" name="lastpage"
                                    placeholder="Ex: 10" min="1" required />
                                <div class="invalid-feedback">Por favor, insira o apelido.</div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-primary">Submeter Pedido</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

biblioteca/templates/custom/list-documents.html
{% extends 'layouts/app.html' %}

{% block title %}Dashboard {% endblock %}

{% block content %}
{% load static %}
<div class="container mt-4">
    <form method="get">
        <div class="d-flex justify-content-between align-items-center mb-3 flex-wrap">
            <div class="btn-group mb-2">
                <input type="radio" class="btn-check" name="type" id="type_all" value="" {% if not request.GET.type %}checked{% endif %}>
                <label class="btn btn-primary btn-sm {% if not request.GET.type %}active{% endif %}" for="type_all">Todos</label>
                <input type="radio" class="btn-check" name="type" id="type_livro" value="livros" {% if request.GET.type == 'livros' %}checked{% endif %}>
                <label class="btn btn-outline-primary btn-sm {% if request.GET.type == 'livros' %}active{% endif %}" for="type_livro">Livros</label>
                <input type="radio" class="btn-check" name="type" id="type_artigo" value="artigos" {% if request.GET.type == 'artigos' %}checked{% endif %}>
                <label class="btn btn-outline-primary btn-sm {% if request.GET.type == 'artigos' %}active{% endif %}" for="type_artigo">Artigos</label>
                <input type="radio" class="btn-check" name="type" id="type_tese" value="teses" {% if request.GET.type == 'teses' %}checked{% endif %}>
                <label class="btn btn-outline-primary btn-sm {% if request.GET.type == 'teses' %}active{% endif %}" for="type_tese">Teses</label>
                <input type="radio" class="btn-check" name="type" id="type_revista" value="revistas" {% if request.GET.type == 'revistas' %}checked{% endif %}>
                <label class="btn btn-outline-primary btn-sm {% if request.GET.type == 'revistas' %}active{% endif %}" for="type_revista">Revistas</label>
            </div>
            <select class="form-select form-select-sm w-auto mb-2" name="order">
                <option selected>Ordenar por: Título</option>
                <option value="title">Titulo</option>
                <option value="type">Tipo</option>
                <option value="author">Autor</option>
                <option value="year">Ano</option>
            </select>
        </div>
        <button type="submit" class="btn btn-sm btn-secondary ms-2">Filtrar</button>
    </form>
</div>
<div class="container-lg py-4">
    <div class="row g-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        <!-- Card exemplo -->
        {% for document in documents %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
            <div class="card h-100 bg-livro">
                <div class="card-body">
                    <div class="text-center mb-2">
                        <i class="fas fa-book fa-2x text-secondary"></i>
                    </div>
                    <h6 class="fw-bold">{{document.title}}</h6>
                    <p class="text-muted small mb-1">{{document.author}}</p>
                    <p class="text-muted small mb-2">{{document.year}}</p>
                    <span class="badge bg-secondary text-light">{{document.type}}</span>
                </div>
                <div class="card-footer bg-white border-0 d-flex justify-content-between">
                    <a href="{% url 'order.submit' id=document.id %}" class="btn btn-sm btn-success">Imprimir</a>
                    <a href="{% url 'documents.read' id=document.id %}" class="btn btn-sm btn-outline-primary">Ler</a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="text-center mt-4">
            <h4>Nenhum Documento foi encontrado</h4>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

biblioteca/templates/custom/order-history.html
{% extends 'layouts/app.html' %}

{% block title %}Pedidos de Impressão {{document.title}} {% endblock %}

{% block content %}
{% load static %}
<div class="row">
    <div class="card shadow border border-0">
        <div class="card-body p-2">
            <div class="d-flex justify-content-between align-items-center">
                <span class="fs-4 fw-bold">Meus Pedidos de Impressão de Documentos</span>
            </div>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <div class="table-responsive">
                <table id="idem-tables" class="table table-bordered table-hover align-middle text-center">
                    <thead class="table-dark">
                        <tr>
                            <th>Id</th>
                            <th>Documento</th>
                            <th>Copias</th>
                            <th>Paginas</th>
                            <th>Status</th>
                            <th>Data</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for order in orders %}
                        <tr>
                            <td>#{{ order.id }}</td>
                            <td>{{ order.document.title }}</td>
                            <td>{{ order.copy_total }}</td>
                            <td>{{ order.first_page }} - {{ order.last_page }}</td>
                            <td>{{ order.get_status_display }}</td>
                            <td>{{ order.created_at|date:"d/m/Y H:i" }}</td>
                        </tr>
                        {% endfor %}
                        <!-- Caso não haja pedidos -->
                        <!--
              <tr>
                <td colspan="8" class="text-muted">Nenhum pedido encontrado.</td>
              </tr>
              -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

biblioteca/templates/custom/read-document.html
{% extends 'layouts/app.html' %}

{% block title %} Ler Documento {% endblock %}

{% block content %}
{% load static %}
<div class="row">
    <embed src="{% static 'pdfjs/web/viewer.html' %}?file={{document.link.url}}" type="application/pdf" width="800px" height="2100px" />
</div>
{% endblock %}